apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejs
  namespace: nodejs
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: nodejs
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: jaydeepuniverse/node-js:3.0
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
