apiVersion: v1
kind: Pod
metadata:
  name: pod-sample-nodejs-labels-selected-node
  namespace: nodejs
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - image: jaydeepuniverse/sample-node-js:3.0
    name: container-pod-sample-nodejs-labels-selected-node
    ports:
    - containerPort: 8080
      protocol: TCP
