apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
spec:
  serviceAccountName: foo
  containers:
  - image: jaydeepuniverse/curl:1.0
    name: main
    command: ["sleep", "9999999"]
  - name: ambassador
    image: jaydeepuniverse/kubectl-proxy:1.0
