apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: mongodb
spec:
  volumes:
  - name: mongodb-data
    azureFile:
      secretName: azure-secret
      shareName: 47184uw2ddevfs1
      readOnly: false
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
