apiVersion: v1
kind: Pod
metadata:
  name: fortune-args
  namespace: fortune
  labels:
    app: fortune
spec:
  containers:
  - image: jaydeepuniverse/fortune:2
    args: ["2"]
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
