apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: mongodb
spec:
  volumes:
  - name: mongodb-data
    azureDisk:
      kind: Managed
      diskName: 47184UW2DDevDDisk1
      diskURI: /subscriptions/751b2a6d-8b9b-4e6e-9588-6b6762b4691d/resourceGroups/47184DevOpsDev/providers/Microsoft.Compute/disks/47184UW2DDevDDisk1
      fsType: ext4
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
