apiVersion: v1
kind: Pod
metadata:
  name: pod-sample-nodejs
  namespace: nodejs-namespace
spec:
  containers:
  - image: jaydeepuniverse/sample-node-js:3.0
    name: container-pod-sample-nodejs
    ports:
    - containerPort: 8080
      protocol: TCP
