apiVersion: v1
kind: Pod
metadata:
  name: downward-volume
  namespace: downward
  labels:
    app: downward
    foo: bar
  annotations:
    key1: value1
    key2: |
      multi
      line
      value2
spec:
  containers:
  - image:  busybox
    name: main
    command: ["sleep", "9999999"]
    volumeMounts:
    - name: downward
      mountPath: /etc/downward
  volumes:
  - name: downward
    downwardAPI:
      items:
      - path: "podName"
        fieldRef:
          fieldPath: metadata.name
      - path: "podNamespace"
        fieldRef:
          fieldPath: metadata.namespace
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
