apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-rc
  namespace: nodejs
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: nodejs-unhealthy-rc
        image: luksa/kubia-unhealthy
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
