apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs
  namespace: nodejs
spec:
  replicas: 3
  selector:
    app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: luksa/kubia
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
