apiVersion: v1
kind: Service
metadata:
  name: fortune-loadbalancer
  namespace: fortune
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  - port: 443
    targetPort: 443
    name: "https"
  selector:
    app: fortune
