apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: mongodb
spec:
  storageClassName: mongodb
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
