apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-sync
  namespace: gitrepo
  labels:
    app: gitrepo-sync
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  - image: openweb/git-sync
    name: gitsync-container
    volumeMounts:
    - name: html
      mountPath: /gitrepo
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/JaydeepUniverse/kubia-website-example.git
    - name: GIT_SYNC_DEST
      value: "/gitrepo"
    - name: GIT_SYNC_BRANCH
      value: "master"
    - name: GIT_SYNC_REV
      value: "FETCH_HEAD"
    - name: GIT_SYNC_WAIT
      value: "10"
  volumes:
  - name: html
    emptyDir: {}
