apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  azureDisk:
    kind: Managed
    diskName: 47184UW2DDevDDisk1
    diskURI: /subscriptions/751b2a6d-8b9b-4e6e-9588-6b6762b4691d/resourceGroups/47184DevOpsDev/providers/Microsoft.Compute/disks/47184UW2DDevDDisk1
    fsType: ext4
